"""Add cascade delete to discussion board relationships

Revision ID: 46107c48081d
Revises: 91d254042545
Create Date: 2025-08-23 10:13:30.749028

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '46107c48081d'
down_revision = '91d254042545'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
