"""Add Translation model

Revision ID: 91d254042545
Revises: ad7db8e91efb
Create Date: 2025-08-07 20:52:45.306732

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '91d254042545'
down_revision = 'ad7db8e91efb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proof_translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(), nullable=False),
    sa.Column('target_language', sa.String(), nullable=False),
    sa.Column('translation_engine', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['proof_pages.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['proof_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proof_translations_author_id'), 'proof_translations', ['author_id'], unique=False)
    op.create_index(op.f('ix_proof_translations_page_id'), 'proof_translations', ['page_id'], unique=False)
    op.create_index(op.f('ix_proof_translations_revision_id'), 'proof_translations', ['revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proof_translations_revision_id'), table_name='proof_translations')
    op.drop_index(op.f('ix_proof_translations_page_id'), table_name='proof_translations')
    op.drop_index(op.f('ix_proof_translations_author_id'), table_name='proof_translations')
    op.drop_table('proof_translations')
    # ### end Alembic commands ###
