version: '3.8'

services:
  kalanjiyam-web:
    image: ${KALANJIYAM_IMAGE}
    container_name: kalanjiyam-web
    ports:
      - host_ip: ${KALANJIYAM_HOST_IP}
        published: ${KALANJIYAM_HOST_PORT}
        target: 5000
    environment:
      - KALANJIYAM_BOT_PASSWORD=insecure bot password
    depends_on:
      - kalanjiyam-db
      - kalanjiyam-redis

  kalanjiyam-db:
    image: postgres:15
    container_name: kalanjiyam-db
    environment:
      - POSTGRES_DB=kalanjiyam
      - POSTGRES_USER=kalanjiyam
      - POSTGRES_PASSWORD=kalanjiyam
    volumes:
      - kalanjiyam-data:/var/lib/postgresql/data

  kalanjiyam-redis:
    image: redis:7
    container_name: kalanjiyam-redis

  kalanjiyam-celery:
    image: ${KALANJIYAM_IMAGE}
    command: celery -A kalanjiyam.tasks worker --loglevel=INFO
    environment:
      - KALANJIYAM_BOT_PASSWORD=insecure bot password
    depends_on:
      - kalanjiyam-db
      - kalanjiyam-redis

volumes:
  kalanjiyam-data:
