#! /usr/bin/bash

KALANJIYAM_DEPLOY_CONFDIR=${HOME}/deploy-config/
KALANJIYAM_WORKSPACE=${HOME}

function usage {
    echo "Usage: $0 -i <image > <command option> # Setup database"
    echo "          -c # Setup directory"
    echo "          -d # Setup database"
    echo "          -l # Status of Kalanjiyam server"
    echo "          -s # Start Kalanjiyam"
    echo "          -x # Stop Kalanjiyam"
    echo "          -v # Show version"
    echo "          -h # Help"
    exit 1
}

function find_unused_port {
    BOTTOM_PORT=5001
    TOP_PORT=5100

    for port in `seq $BOTTOM_PORT $TOP_PORT`
    do
        echo "hello" > /dev/tcp/$KALANJIYAM_HOST_IP/$port
        if [ "$?" -ne 0 ]
        then
            echo "$port"
            return
        fi
    done
    echo "Error! No unused ports found between $BOTTOM_PORT-$TOP_PORT"
    exit 1
}

function init_staging_env {
    
    if [ -z "$KALANJIYAM_STAGING_DIR" ]
    then
        exit "Error! Invalid staging directory"
        exit 1
    fi
    
    mkdir -p "$KALANJIYAM_STAGING_DIR"
    if [ "$?" -ne 0 ]
    then
        echo "Error! staging directory -- $KALANJIYAM_STAGING_DIR -- create failed."
        exit 1
    else
        echo "export KALANJIYAM_STAGING_DIR=$KALANJIYAM_STAGING_DIR" >> $KALANJIYAM_STAGING_ENV
        echo "> Change directory to $KALANJIYAM_STAGING_DIR"
    fi
    
    
    echo "export KALANJIYAM_HOST_IP=$(ip route get 1 | awk '{print $7; exit}')" >> $KALANJIYAM_STAGING_ENV
    source $KALANJIYAM_STAGING_ENV

    echo "export KALANJIYAM_HOST_PORT=$(find_unused_port)" >> $KALANJIYAM_STAGING_ENV

    if [ -z "$KALANJIYAM_IMAGE" ]
    then
        echo "Error! Invalid KALANJIYAM_IMAGE"
        exit 1
    else
        echo "export KALANJIYAM_IMAGE=$KALANJIYAM_IMAGE" >> $KALANJIYAM_STAGING_ENV
    fi
}

function setup_staging {
    if [ ! -e "$KALANJIYAM_STAGING_ENV" ]
    then
        echo "Error! Invalid Kalanjiyam staging environment."
        exit 1
    fi
    source $KALANJIYAM_STAGING_ENV
    cd $KALANJIYAM_STAGING_DIR
}

function setup_database {
    docker compose -f ${KALANJIYAM_DEPLOY_CONFDIR}/docker-compose-dbsetup.yml up
    echo "> Kalanjiyam Database...UP"
}

function start_webapp {
    docker compose -f ${KALANJIYAM_DEPLOY_CONFDIR}/docker-compose.yml up --detach
    echo "> Kalanjiyam URL........http://${KALANJIYAM_HOST_IP}:${KALANJIYAM_HOST_PORT} is UP"
}

function start_kalanjiyam {
    docker compose -f ${KALANJIYAM_DEPLOY_CONFDIR}/docker-compose.yml up --detach
    if [ "$?" -ne 0 ]
    then
        echo "Error! > Kalanjiyam URL........http://${KALANJIYAM_HOST_IP}:${KALANJIYAM_HOST_PORT} failed"
        exit 1
    fi
    echo "> Kalanjiyam URL........http://${KALANJIYAM_HOST_IP}:${KALANJIYAM_HOST_PORT} is UP"
}

function stop_kalanjiyam {
    docker compose -f ${KALANJIYAM_DEPLOY_CONFDIR}/docker-compose.yml stop && docker compose -f ${KALANJIYAM_DEPLOY_CONFDIR}/docker-compose.yml rm -v -s -f
    if [ "$?" -ne 0 ]
    then
        echo "Error! > Kalanjiyam URL........http://${KALANJIYAM_HOST_IP}:${KALANJIYAM_HOST_PORT} failed to stop"
        exit 1
    fi
    
    cd $(dirname "${KALANJIYAM_STAGING_DIR}")
    echo "Removing $KALANJIYAM_STAGING_DIR"
    rm -rf $KALANJIYAM_STAGING_DIR
    docker image rm $KALANJIYAM_IMAGE
    echo "Kalanjiyam URL http://${KALANJIYAM_HOST_IP}:${KALANJIYAM_HOST_PORT} is STOPPED"
}


function status_kalanjiyam {
    docker compose -f ${KALANJIYAM_DEPLOY_CONFDIR}/docker-compose.yml ps
    if [ "$?" -ne 0 ]
    then
        echo "Error! > Kalanjiyam URL........http://${KALANJIYAM_HOST_IP}:${KALANJIYAM_HOST_PORT} failed to stop"
        exit 1
    fi
    
    echo "http://${KALANJIYAM_HOST_IP}:${KALANJIYAM_HOST_PORT}"
}


# Main

while getopts "i:dlsxh" op; do
    case "${op}" in
        
        d)
            setup_staging
            setup_database
            ;;
        i)
            export KALANJIYAM_IMAGE=$OPTARG
            export KALANJIYAM_STAGING_DIR=${KALANJIYAM_WORKSPACE}/${KALANJIYAM_IMAGE#ghcr.io/AnaadiAI/kalanjiyam:}
            export KALANJIYAM_STAGING_ENV=$KALANJIYAM_STAGING_DIR/.env
            ;;
        l)
            setup_staging
            status_kalanjiyam
            ;;
        s)
            init_staging_env
            setup_staging 
            start_ambuda
            ;;
        x)
            setup_staging
            stop_ambuda
            ;;
        *)
            usage
            ;;
    esac
done

exit 0