# Build release image. Push image to ghcr.io. Deploy on staging environment.

name: Release image build & publish
env:
  KALANJIYAM_VERSION: v0.1
  KALANJIYAM_HOST_IP: 127.0.0.1
  KALANJIYAM_HOST_PORT: 5090
  REGISTRY: ghcr.io
  
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'release'
    types: [opened, reopened, synchronize]

jobs:
  push_to_registries:
    name: Push Kalanjiyam image to GH container registry
    runs-on: ubuntu-22.04
    environment: staging
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: GH container registry login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,event=pr,value=v0.1-pr${{ github.event.pull_request.number }}
            type=ref,event=branch,value=v0.1-{{branch}}-{{sha}}
            type=raw,event=push,value=v0.1-{{branch}}-{{sha}}
            
      - name: Extract Image Id
        id: image_id
        shell: bash
        run: |
          echo "KALANJIYAM_IMAGE=${{ env.KALANJIYAM_IMAGE }}" >> $GITHUB_ENV
          echo "${{ env.KALANJIYAM_IMAGE }}" >> image-name
        env:
          KALANJIYAM_IMAGE: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
      
      - uses: actions/upload-artifact@v3
        with:
          name: image-name
          path: image-name
      
      - name: Build and push Docker images
        id: publish
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: build/containers/Dockerfile.final
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Run SQL db setup
        id: dbsetup
        run: docker compose -f deploy/local/docker-compose-dbsetup.yml up
          
      - name: Run Docker images
        id: deploy
        run: docker compose -f deploy/local/docker-compose.yml up --detach
        env:
          KALANJIYAM_HOST_IP: 0.0.0.0
          
      - name: Check that site is running
        run: timeout 2m bash -c "until curl --fail-with-body $KALANJIYAM_HOST_IP:$KALANJIYAM_HOST_PORT; do sleep 1; done"
        
      - name: Show logs on fail
        if: ${{ failure() }}
        run: docker compose -f deploy/local/docker-compose.yml logs

  pr_commented:
    # This job only runs on PR open or reopen
    name: PR comment
    needs: push_to_registries
    if: ${{ github.event.issue.pull_request.opened || github.event.issue.pull_request.reopened }}
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: 'Your pull request is open. Reviewers will review the pullrequest at the earliest.'
          reactions: '+1'
  
  deploy_staging:
    name: Run staging deploy
    needs: push_to_registries
    runs-on: [self-hosted, staging, linux]
    environment: staging
    steps:
      - uses: actions/download-artifact@v3
        id: image-name
        with:
          name: image-name

      - name: extract_image_details
        shell: bash
        run: |
          echo "KALANJIYAM_IMAGE=`cat image-name`" >> $GITHUB_ENV
          echo "KALANJIYAM_IMAGE_TAG=${KALANJIYAM_IMAGE#ghcr.io/AnaadiAI/kalanjiyam:}" >> $GITHUB_ENV
          cat image-name

      - name: Start the deploy job
        id: stagingdeploy
        run: bash /home/kalanjiyam-devbot/bin/kalanjiyam-runner -i ${{ env.KALANJIYAM_IMAGE }} -s
      
